### ISSUE TITLE
Make deprecated table attributes optional

### ISSUE THREAD

**Issue by coryschires** [rohit-prajapati/html-tablify#3]
Hi! thanks for writing this library! It has saved me a lot boring code by making it really easy to generate HTML tables.

I have a small suggestion. It looks like the generated HTML automatically includes table attributes of `border`, `cellpadding`, and `cellspacing`. As far as I can tell, all of [these attributes have been deprecated in HTML5](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table). Instead, they suggest you use CSS. 

For this reason, I think these attributes should be optional (ideally disabled by default). Of course I can't say for sure, but I suspect most users would be comfortable (and perhaps even prefer) styling the tables directly via CSS. 

If you're open to this suggestion, please let me know, as I would be happy to make a pull request.

Thanks again!

**Comment by rohitprajapati** [comment]
Hi @coryschires, thanks for your suggestion. Please raise the pull request.

**Comment by coryschires** [comment]
Hi @rohitprajapati 

Our use case has changed slightly, and I now want those attributes. In other words, turns out I want the current behavior. 

That said, I think the suggestion is still sound. But unfortunately, making a PR has become a much lower priority for me. I may follow up with a PR at some point but I wouldn't count on it any time soon. 

Thanks for the quick reply and feel free to close this issue, if you wish.
