### ISSUE TITLE
To apply styling (css) use 'css' in options - This option is not working

### ISSUE THREAD

**Issue by Anshul-Sonpure** [rohit-prajapati/html-tablify#5]
Hey Rohit,
Thanks for writing this beautiful js code and it is really a lifesaver in converting JSON to HTML. But as earlier Cory Schires raised this concern that users should be able to add CSS in HTML so that it looks a little bit more attractive and beautiful.
However, I tried using css option but it was not working digging into why things were not reflected I noticed that css varible was not defined and neither used.
`function tablify(options) {
    options = options || {};
    var tableData = options.data || [];
    var header = options.header;
    var border = isDefined(options.border) ? options.border : 1;
    var cellspacing = isDefined(options.cellspacing) ? options.cellspacing : 0;
    var cellpadding = isDefined(options.cellpadding) ? options.cellpadding : 0;
    var tableId = options.table_id || 'tablify';
    var tableClass = options.table_class || 'tablify';
    var header_mapping = options.header_mapping || {};
    var pretty = options.pretty;
    if (pretty === undefined) {
        pretty = true;
    }` 
    it would great if you can include how we can add css to the table that is generated.

Thanks in advance,
:)

**Comment by rohitprajapati** [comment]
Ohh that was a miss. Sure will add this. Thanks for raising the concern.

**Comment by rohitprajapati** [comment]
Hi Anshul, I have added the support of CSS as a patch version.

**Comment by Anshul-Sonpure** [comment]
Thanks a lot, Rohit but I see you made changes and deployed them on GitHub can you please do the same on https://www.npmjs.com/package/html-tablify.
As I see on the npm side the code is still the old one.

**Comment by rohitprajapati** [comment]
Hi Anshul, forgot to do that. I have pushed the changes to npm as well. Thanks for reminding me.
