### ISSUE TITLE
Cell level css?

### ISSUE THREAD

**Issue by wmelton** [rohit-prajapati/html-tablify#6]
This library is great and does exactly the job needed for converting json to a quick table. Would it be possible to support cell-level css styling?

Use case: Suppose we have two columns, ["budget", "actual"]. In our json object, perhaps if "actual" is less than "budget" we would want to specify, "css: "background-color: red;" so that cell could be colorized. 

Is there any interest in adding something like this?

**Comment by rohitprajapati** [comment]
Thanks for writing @wmelton . Currently there is no direct cell level CSS class but you can use following to apply CSS to a particular cell or group of cells -

1. options.css -

```
var options = {
    data: [{a: 1, b: 2}, {b: 1, a: 2}, {a: 4, c: 5}],
    css: `table tbody tr:nth-child(2) td:nth-child(3) {
                    background-color: red;
             }`
};
```

2. options.table_class -

```
var options = {
    data: [{a: 1, b: 2}, {b: 1, a: 2}, {a: 4, c: 5}],
    css: `tableClass`
};
```
And in your CSS file add styling like -
```
.tableClass tbody tr:nth-child(2) td:nth-child(3) {
    background-color: red;
  }
```
