### ISSUE TITLE
Update mocha to patch vulnerabilities?

### ISSUE THREAD

**Issue by cvaldezUM** [rohit-prajapati/html-tablify#7]
**Is it possible to update your dependency on mocha 2.5.3?**
  
Critical        Prototype Pollution in minimist

  Package         minimist

  Patched in      >=1.2.6

  Dependency of   html-tablify

  Path            html-tablify > mocha > mkdirp > minimist

  More info       https://github.com/advisories/GHSA-xvch-5gv4-984h

  Moderate        Prototype Pollution in minimist

  Package         minimist

  Patched in      >=0.2.1

  Dependency of   html-tablify

  Path            html-tablify > mocha > mkdirp > minimist

  More info       https://github.com/advisories/GHSA-vh95-rmgr-6w4m

  High            Regular Expression Denial of Service (ReDoS)

  Package         diff

  Patched in      >=3.5.0

  Dependency of   html-tablify

  Path            html-tablify > mocha > diff

  More info       https://github.com/advisories/GHSA-h6ch-v84p-w6p9

  High            Regular Expression Denial of Service in minimatch

  Package         minimatch

  Patched in      >=3.0.2

  Dependency of   html-tablify

  Path            html-tablify > mocha > glob > minimatch

  More info       https://github.com/advisories/GHSA-hxm2-r34f-qmc5

  Low             Regular Expression Denial of Service in debug

  Package         debug

  Patched in      >=2.6.9

  Dependency of   html-tablify

  Path            html-tablify > mocha > debug

  More info       https://github.com/advisories/GHSA-gxpj-cx7g-858c

Thanks in advance.

**Comment by rohitprajapati** [comment]
Thanks for asking. 

Updated to mocha@10.0.0

Please use html-tablify@2.0.4

**Comment by cvaldezUM** [comment]
Thank you so much!
Have a nice day.
